// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo2suKjhRiqBBSQrm2XkvllmDGzdINx4I',
    appId: '1:541388242989:web:34ea6397473ff937c7b8a4',
    messagingSenderId: '541388242989',
    projectId: 'whatasapp-shourya',
    authDomain: 'whatasapp-shourya.firebaseapp.com',
    databaseURL: 'https://whatasapp-shourya-default-rtdb.firebaseio.com',
    storageBucket: 'whatasapp-shourya.appspot.com',
    measurementId: 'G-LY3SHFGGPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsxgb-NcU3Vhz_rH76LX83JUq2BfmC25k',
    appId: '1:541388242989:android:05d5f121d519a91ac7b8a4',
    messagingSenderId: '541388242989',
    projectId: 'whatasapp-shourya',
    databaseURL: 'https://whatasapp-shourya-default-rtdb.firebaseio.com',
    storageBucket: 'whatasapp-shourya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUm7mhgt8Ip0dQJ0qOUlZuHrumj5P0TJU',
    appId: '1:541388242989:ios:c2a58dbeaf254cfdc7b8a4',
    messagingSenderId: '541388242989',
    projectId: 'whatasapp-shourya',
    databaseURL: 'https://whatasapp-shourya-default-rtdb.firebaseio.com',
    storageBucket: 'whatasapp-shourya.appspot.com',
    androidClientId:
        '541388242989-jp00h00nbatjpoaafojge0ocsjvq0vg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.assBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUm7mhgt8Ip0dQJ0qOUlZuHrumj5P0TJU',
    appId: '1:541388242989:ios:c2a58dbeaf254cfdc7b8a4',
    messagingSenderId: '541388242989',
    projectId: 'whatasapp-shourya',
    databaseURL: 'https://whatasapp-shourya-default-rtdb.firebaseio.com',
    storageBucket: 'whatasapp-shourya.appspot.com',
    androidClientId:
        '541388242989-jp00h00nbatjpoaafojge0ocsjvq0vg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.assBlogApp',
  );
}
